# Generated by Django 4.0.3 on 2022-03-19 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_name", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=20)),
                ("last_name", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "manager"),
                            ("sales", "sales"),
                            ("support", "support"),
                        ],
                        default="else",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("potential", "potential"), ("existing", "existing")],
                        default="potential",
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("mobile", models.CharField(max_length=20)),
                ("compagny", models.CharField(max_length=50)),
                ("date_created", models.DateField(auto_now=True)),
                ("date_updated", models.DateField(auto_now=True)),
                (
                    "sales_contact",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "sales"},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="client_sales_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "support"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="client_support_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventStatu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in process", "in process"),
                            ("finished", "finished"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField(auto_now=True)),
                ("date_updated", models.DateField(auto_now=True)),
                ("attendees", models.IntegerField()),
                ("date", models.DateField(auto_now=True)),
                ("notes", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.client"
                    ),
                ),
                (
                    "event_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.eventstatu",
                    ),
                ),
                (
                    "sales_contact",
                    models.ForeignKey(
                        limit_choices_to={"role": "sales"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event_sales_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        limit_choices_to={"role": "support"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event_support_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField(auto_now=True)),
                ("date_updated", models.DateField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("signed", "signed"), ("not signed", "not signed")],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("payment_due", models.DateField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.client"
                    ),
                ),
                (
                    "sales_contact",
                    models.ForeignKey(
                        limit_choices_to={"role": "sales"},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="contract_sales_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        limit_choices_to={"role": "support"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="contract_support_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
