# Generated by Django 4.0.3 on 2022-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contract_date_created_contract_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('finished', 'finished')], max_length=20),
        ),
    ]
