# Generated by Django 4.0.3 on 2022-03-15 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='support',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('potential', 'potential'), ('existing', 'existing')], default='potential', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='support_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_support_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='support_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_support_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'sales'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_sales_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_support_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'sales'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_sales_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'sales'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_sales_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('in process', 'in process'), ('finished', 'finished')], max_length=20),
        ),
    ]
