# Generated by Django 4.0.3 on 2022-03-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_client_sales_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventStatus',
            new_name='EventStatu',
        ),
    ]
