# Generated by Django 4.0.3 on 2022-03-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('sales', 'sales'), ('support', 'support')], default='else', max_length=20),
        ),
    ]
