# Generated by Django 4.0.3 on 2022-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
