# Generated by Django 4.0.3 on 2022-03-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_date_created_and_more'),
        ('event', '0002_alter_event_date_alter_event_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contract.contract'),
        ),
    ]
